# fly.toml app configuration file generated for adsights-cuda-vector-add-test on 2025-01-28T11:12:17-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'adsights-cuda-vector-add-test'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'a10'
