# fly.toml app configuration file generated for adsights-cuda-vector-add-test-summer-pine-772 on 2025-01-28T12:37:54-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'adsights-cuda-vector-add-test-summer-pine-772'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'a10'
